### ISSUE TITLE
Implement a snackbar notification system

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#107]
Maybe [`renderless-svelte`](https://github.com/stephane-vanraes/renderless-svelte) will come in handy here.

**Acceptance criteria**:
- the `features` layer should have access to a function that initiates a snackbar display
- the snackbar should stay displayed for 4000ms and then disappear automatically
- the snackbar should be able to display an arbitrary text message and support a button with a customizable text to call a passed callback on click
- unit tests are provided
- the snackbar looks identical to the proposed design:
  <img width="304" alt="image" src="https://user-images.githubusercontent.com/15035286/156981261-6e64b961-5fa2-4b2d-aa34-b0729819c48c.png">

**Comment by VanishMax** [comment]
@illright question: what should the callback on a "sign in" button do? Authenticate by GitHub or redirect to the `/library` page?

**Comment by illright** [comment]
@VanishMax This should not be part of the task, you only need to implement a component that would accept any callback.

Answering your question: I think it should authenticate
