### ISSUE TITLE
Notify the user when their likes are not synced

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#137]
Blocked by #107 

According to the design, pressing the like button should trigger a snackbar that tells the user they should sign in if they want their likes synced.

**Acceptance criteria**:
- if and only if the user is not signed in, if the user has never seen this message previously, pressing a like button should result in a snackbar
- the snackbar text and action should follow the proposed design
- the action button on the snackbar should sign the user in directly, without leading them to the Your Library page
- a successful sign in from the snackbar action should result in another snackbar without actions that reads "Successfully signed in as **\@\<username\>**"
- the snackbar should not be shown twice on the same device

**Comment by khaledismaeel** [comment]
> the snackbar should not be shown twice on the same device

Do you mean that a certain device receives the snackbar only once ever?
