### ISSUE TITLE
Set up performance testing with Lighthouse CI

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#159]
You can use [this pre-built GitHub Action](https://www.foo.software/docs/lighthouse-check-github-action/intro)

**Acceptance criteria**:
- [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci) is set up to run on each PR and send the results as a comment
- Lighthouse reports are available as artifacts to the workflow run
- If our scores are good enough, configure reasonable thresholds to fail the build if it's not met

**Comment by VanishMax** [comment]
As usual, I've found a pretty buggy issue to do 🤣 

Didn't finish with researching, but submitted [an issue](https://github.com/zentered/cloudflare-preview-url/issues/40) to the GitHub action that we could possibly use to make the performance metrics more real.

**Comment by illright** [comment]
@VanishMax here's also a pointer — deployments from branches have aliases, for example, your PR's deployment is accessible at https://feature-performance-tests.cast-iu.pages.dev/

Reference: https://developers.cloudflare.com/pages/platform/preview-deployments/#preview-aliases
