### ISSUE TITLE
Fix performance testing

### ISSUE THREAD

**Issue by VanishMax** [aabounegm/cast#167]
For now, performance testing uses `present: 'lighthouse:recommended'`, which sets the recommended configurations to the `lighthouserc.json`. Our application cannot handle them for now, thus [the CI fails](https://github.com/aabounegm/cast/runs/5750907336?check_suite_focus=true).

The task is to fix these issues or configure the `assess` field, so the CI will pass successfully.

Acceptance criteria:
* CI passes
* Problematic points are fixed or the threshold for them is changed in the `assess` field of the Lighthouse config. Also, it would be nice to write a description in this PR of why the threshold has been changed.

**Comment by VanishMax** [comment]
One more thing to do here is to check the checkbox in our Readme about Lighthouse tests

**Comment by illright** [comment]
That's done already

**Comment by VanishMax** [comment]
Wait, is it different for us?

<img width="688" alt="image" src="https://user-images.githubusercontent.com/29180358/161680244-b8ca48ac-6274-4d8b-b622-169afec58b0a.png">

**Comment by illright** [comment]
Oh, sorry, forgot that it is still not merged
