### ISSUE TITLE
Identify the key requirements of our app to test E2E

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#176]
Requirements, user stories, flows, functional requirements, whatever you wanna call it. List all of them.

Rule of thumb: if we make sure those requirements are met, the users of the app should be able to _fully_ do all of the 5 features that we listed

Artifacts:
* A list of requirements

**Comment by VanishMax** [comment]
**Here is a list of user stories and their sub-stories that could be translated into meaningful E2E tests**

### Audio listening

* Ability to look through the podcasts and their episodes
* Ability to listen the episode without pausing when leaving the page
* Ability to scrub the audio, pause, go 10 seconds back and forward in time, increase and decrease the audio speed
* Ability to read the audio transcript

### Authentication
* Ability to Log In using GitHub
* Synchronisation of listening history and episode likes with the account, so the data is persistent on different users' devices
* Ability to Log Out

### Audio download and offline listening

* Ability to download the episodes when online
* Ability to listen to downloaded episodes when offline

### Episode likes

* Ability to like an episode and see it in the personal gallery
* Ability to remove the like from an episode
* Liked episodes are persistent in users' browser if they are not authorized

### Keeping the list of recently played podcasts

* Podcasts listened recently are persistent in users' browser if they are not authorized
* Only {amount} of recently listened podcast are stored
