### ISSUE TITLE
Fix the icon assets for PWA

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#183]
On Android, the icon looks pixelated. Also, on the splash screen, it's very tiny. Maybe we could set up some sort of automatic build process to create images of required resolution (but I don't think that's highly probable)

**Comment by aabounegm** [comment]
But I thought SVG icons are supported, how could it be pixelated?
Anyway, I think an automated build process would be an overkill, and I suggest [PWABuilder](https://www.pwabuilder.com/imageGenerator) or [Manifest Generator](https://manifest-gen.netlify.app/).
