### ISSUE TITLE
Fix the app icon in the GitHub application 

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#198]
When creating a GitHub app for OAuth, you can specify an icon. Let's give our brand some flair and set the proper icon there

**Comment by khaledismaeel** [comment]
GitHub does not provide an option to set different zooms for the application icon and badge, so this is what they look like right now. Personally I think it's horrible, but we'll have to make do with it.

![image](https://user-images.githubusercontent.com/62155849/163707245-ca3b2326-b2c3-4282-864d-214988340482.png)

**Comment by illright** [comment]
Maybe we could set a white background? Or a lighter shade of this blue?

**Comment by khaledismaeel** [comment]
![image](https://user-images.githubusercontent.com/62155849/164093114-7188c1d6-1425-4682-9549-b60050092ceb.png)

That's the best I could get given GitHub's weird aspect.

**Comment by illright** [comment]
Honestly, I don't like this. It's too little padding around the content of the icon. Honestly, I'd prefer if you just exported the circular version of the icon with a completely opaque border and selected #ffffff as the background color as is right now

**Comment by khaledismaeel** [comment]
![image](https://user-images.githubusercontent.com/62155849/164319714-fe17a28e-e331-484e-b55f-b879a6eee2c7.png)

I got into a dilemma choosing between centering the icon's concentric circles or setting uniform padding along all sides. I think this one is cooler. What do you think?

And yeah, I took the liberty to invert the colors and get rid of the gradient.

**Comment by illright** [comment]
Yeah, it's good enough. Case closed
