### ISSUE TITLE
Create the presentation

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#211]
**Acceptance criteria**:
- [x] a slide about the project (list of features, external API)
- [x] a slide about the team (who did what)
- [x] a slide for static testing (ESLint, Prettier, TypeScript)
- [x] a slide for unit testing
- [x] a slide for end-to-end testing
- [x] a slide for UI testing with Applitools
- [x] a slide for security testing (access control, fuzz testing, CodeQL, manual)
- [x] a slide for performance testing
- [x] a slide for exploratory testing
- [x] a slide for uptime monitoring with email notifications for quick recovery
- [x] a slide for CI/CD (static testing, test suites, code coverage, performance benchmark, automated review assignment, deployment)
- [x] a slide about our team organization, development processes, architecture
- [x] a slide about how our project evolved over time
- [x] the lessons we learnt

**Comment by illright** [comment]
**Lessons I've learned**:
- a fixed architecture prevents a lot of debate about code structure
- managing a team completely asynchronously is much harder, people are motivated by working with other people
- writing tests for each PR separately makes the process of writing tests more enjoyable

**Comment by VanishMax** [comment]
What I've learned:
- Fontsource library
– How to check security of a website with OWASP checklist
– More Web and JS APIs. For example, how to use Map, Set, URL constructors
– How to cache and serve images of different sizess and formats
– How and, most importanty, when to use fuzz testing
– How to set up the performance testing with Lighthouse
– Jest, Testing library
– How to set up uptime monitor and add badges to the README
– How to use `unplugin-icons` to get an icon efficiently from different icon sets
– How to follow the Feature-Sliced design

And some thoughts:
- Conventional comments are a perfect way to communicate professionally and politely
- Writing tests is sometimes a complicated process, but it brings you many benefits

**Comment by aabounegm** [comment]
**Lessons I learned**:
- Testing is actually important and helps find errors you didn't expect
- The importance of a proper architecture and design from the beginning
- Pair programming is helpful to productivity and bug-hunting
- Effective documentation and communication are essential
- & Some new technologies

**Comment by alkaitagi** [comment]
**Learned**

* Testing with JEST
* Feature-Slised design
* Conventional comments

**Comment by illright** [comment]
#208 contains a summary of exploratory testing
