### ISSUE TITLE
Extend the database to support cover art URL fields for podcasts

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#41]
This is for **podcasts**, not episodes. Also throw in a string field for storing the author.

**Acceptance criteria**:
* Each podcast has a field for the URL to a cover art
* Each podcast has a field for the author

**Comment by VanishMax** [comment]
Done! Added the `cover_url` and `author` VARCHAR fields

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/29180358/154487705-413e4c0a-c794-446d-a01c-3a3ad5849d4a.png">
