### ISSUE TITLE
Configure uptime monitoring

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#47]
Use [Upptime](https://upptime.js.org/).

**Acceptance criteria**:
- a status page is available via GitHub Pages
- badges of uptime percentage and response time are available in the README
- a link to the status page is available in the README by clicking on badges
- uptime alerts are sent to GitHub Issues

**Comment by aabounegm** [comment]
I'm a little confused about how to implement this. Their documentation says that I must create the repo from template, but I doubt that we need all of those folders (`api`, `assets`, `graphs`, `history`), and if they **are** required to be in the repo root, then this is just really ugly.
On the other hand, when I check the defined workflows, it appears that all of the Actions there (and they are a lot) are autogenerated and I shouldn't touch them manually, but I couldn't generate them myself. When I tried the command from the repo it mentioned (`npx @upptime/uptime-monitor`), all I got was `command not found: uptime-monitor`.
Any suggestions?

**Comment by illright** [comment]
Yeah, it's kinda messed up. This probably needs some more investigation. If you don't feel like it, maybe you could configure some other free uptime monitor

**Comment by aabounegm** [comment]
I checked a few other tools, such as the following:
- [UptimeRobot](https://uptimerobot.com/)
- [Better Uptime](https://betteruptime.com/)
- [Freshping](https://www.freshworks.com/website-monitoring/free-uptime-monitoring/)
- [StatusCake](https://www.statuscake.com/)

However, none of them provided a nice integration with GitHub Issues or Pages or badges. Most of them host their own status page and send emails (or Slack messages or otherwise) when the website is down.

I also went through the documentation of Upptime, but couldn't find a way to customize the root folder or branch to operate on, which means that the best option is to have a dedicated repo for that (I don't wanna litter our main repo with automated commits every 5 mins), but it just doesn't feel like it's worth it.
I think we either write our own custom solution or just drop it altogether.

**Comment by illright** [comment]
> However, none of them provided a nice integration with GitHub Issues or Pages or badges.

That's not a problem, those acceptance criteria were written with Upptime in mind. If we're not using it, it's fine to receive alerts in Telegram and have a dedicated status page that's not running on GitHub Pages

> I think we either write our own custom solution

Was actually thinking about it, but I certainly don't feel like doing it within this project

**Comment by aabounegm** [comment]
> those acceptance criteria were written with Upptime in mind

I understand, but they were still nice-to-haves. Without them, we don't really have anything to show on our README (which is the frontpage).
Also, we are using CloudFlare Pages, which are supposed to have ~100% uptime anyway, so with nothing to show off on the presentation, it just becomes useless, imo.

Vote 💧 if you think we should **drop** this, or ⬆️ if you think we should still add **up**time monitoring

**Comment by illright** [comment]
>  with nothing to show off on the presentation

A beautiful status page with 100% uptime is quite the something to show off on the presentation

**Comment by VanishMax** [comment]
@illright @aabounegm I've played for a while with different Upptime configurations and other tools, and I agree with @aabounegm that the only option to use Upptime is with the separate repo. 

However, I have create a demo private repo and added this GitHub workflow with [the action](https://github.com/srt32/uptime):

<img width="505" alt="image" src="https://user-images.githubusercontent.com/29180358/155837197-be2afd6a-d560-485e-9b89-de87902fef9d.png">

Having this, we can add the badge:

<img width="917" alt="image" src="https://user-images.githubusercontent.com/29180358/155837210-022b3af6-2b64-47f6-8fc5-f2a3592e2ffe.png">

I know this is not the "Uptime: 100%" badge, but supposedly there are no good integrations with GitHub actions. I would appreciate if you explain how can we integrate external services like "UptimeRobot" into our project.

Also, notice the "Log success/failure" jobs in the workflow. We could use it to do custom behaviour for checking the uptime. If you have any ideas, feel free to add them here.
