### ISSUE TITLE
Construct the bottom bar

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#56]
Blocked by #26. No animation is required, no drag-to-close functionality either. The markup of the bar has already been provided by @alkaitagi.

**Acceptance criteria**:
- It should look identical to the [proposed design](https://www.figma.com/file/zW1IL7EyYP0lphxDvTvWVu/Cast-%E2%80%93-a-web-podcast-listening-app?node-id=46%3A2308)
- It should feature links to navigate to "Podcast Gallery" and "Your Library" pages
- It should indicate what page the user is currently on (Podcast Episodes is a sub-page of the two pages I mentioned previously)
- It should indicate whether an episode is currently loaded for playing
- It should open the Now Playing widget over the current page by clicking the mini-player
- It should close the Now Playing widget by clicking on the "chevron down" icon
- It should be a part of the layout (meaning it should appear on every page)

**Comment by aabounegm** [comment]
> - It should feature links to navigate to "Podcast Gallery" and "Your Library" pages
> - It should indicate what page the user is currently on (Podcast Episodes is a sub-page of the two pages I mentioned previously

But the Podcast gallery page is just the root `/`, and every page (including the library) is a subpage of that. What should I do in that case?

> - It should open the Now Playing widget over the current page by clicking the mini-player

When clicking what part of it? Should clicking the "seek" or "pause/play" buttons also open it? Or does it only open when clicking the episode icon?

> - It should close the Now Playing widget by clicking on the "chevron down" icon

Shouldn't that be part of the Now Playing widget itself?

**Comment by illright** [comment]
> and every page (including the library) is a subpage of that

It may be a sub-page of the Podcast Gallery in terms of pathnames, but not in terms of the app logic. I think it's alright to have Podcast Gallery at `/`, Your Library at `/library`, Podcast Episodes at `/podcast/:id/`

> Or does it only open when clicking the episode icon?

Well, mainly the cover art, yeah, but you can attach a click listener to the whole thing and have the buttons intercept the click

> It should close the Now Playing widget by clicking on the "chevron down" icon

It's a part of embedding the Now Playing widget. Khaled didn't do this part, he just built out the widget in isolation
