### ISSUE TITLE
Track liked episodes locally

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#57]
Partially blocked by #42. Use [`svelte-persistent-writable`](https://github.com/cdellacqua/svelte-persistent-writable).

**Acceptance criteria**:
- The likes are restored after a page reload within a single browser
- The like button works on the Now Playing page
- New likes are written to the `localStorage`
- Liked episodes are marked prominently on the **Podcast Episodes** page
- **Your Library** page displays the podcasts that have liked episodes

**Comment by aabounegm** [comment]
Isn't this also **fully** blocked by #43?

**Comment by illright** [comment]
Not fully, you can still implement the store and design an interface for it
