### ISSUE TITLE
Add `svelte-check` to the pre-commit hook

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#64]
Currently, our pre-commit hook checks for ESLint issues and formatting problems. However, TypeScript errors go through freely. Remedy that by adding a `pnpm exec svelte-check [...]` to the `.husky/pre-commit` file.

P.S. Also an embarrassing detail: our `pre-commit` hook doesn't even run currently because it's not marked as executable. Please, mark it as executable while you're at it.

**Comment by aabounegm** [comment]
> our `pre-commit` hook doesn't even run currently because it's not marked as executable

Are you referring to the `x` bit of the file permissions on Linux? If so, someone else would need to do that since I use Windows and it is working fine 😁

**Comment by illright** [comment]
> Are you referring to the x bit of the file permissions on Linux?

Yes
