### ISSUE TITLE
Move the `svelte-check` step to the `pre-push` hook

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#88]
Steps:
1. Remove the line that runs `svelte-check` from `.husky/pre-commit`
2. Run `pnpm exec husky add .husky/pre-push <that command from pre-commit that runs svelte-check>`
No need to mess around with permission bits

**Comment by aabounegm** [comment]
Oops, I pushed directly to `main` instead of a branch. Don't know how it didn't reject the push (I didn't even `--force` it). Anyway, I figured out how to modify the permission bits from git's CLI on Windows as well, so hopefully it's fine
