### ISSUE TITLE
Fix the linting command to fail if any of the subcommands fail

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#90]
Currently, the `lint` script runs 3 things, chaining them with `;`. In shell terms this means "disregard the exit code of the first 2 commands and use the exit code of the last command as the final exit code". Hence, when ESLint or Prettier fail, but `svelte-check` passes, we get a passing workflow.

An obvious solution would be to chain the commands with `&&`, but the problem with that is that a failing command prevents all of the subsequent commands from running. When using the `lint` script locally, it's nice to see problems from all 3 tools to take parallel action.

Having said that, do some research for cool ways to propagate non-zero exit codes without breaking the command chain. Maybe something in shell syntax or some package from npm. If nothing fits, fall back to `&&`.

**Comment by aabounegm** [comment]
Actually, `&&` wouldn't work on Windows with PowerShell. I suggest using some package like [`npm-run-all`](https://www.npmjs.com/package/npm-run-all)
