### ISSUE TITLE
Implement GitHub authentication in Supabase

### ISSUE THREAD

**Issue by illright** [aabounegm/cast#99]
Research how to return the user to localhost and preview deployments

**Acceptance criteria**:
- Have a user table that creates users from GitHub logins
- Support login with GitHub

**Artifacts**:
- an endpoint that the frontend can hit in order to authenticate a user

**Comment by khaledismaeel** [comment]
Done. Pair programmed with @aabounegm. The following code can be used to test it:

```js
import { supabaseClient } from '$lib/shared/api';

supabaseClient.auth.onAuthStateChange(console.log);

async function logUp() {
  const { user, session, error } = await supabaseClient.auth.signIn(
    {
      provider: 'github',
    },
    {
      redirectTo: window.location.href,
    }
  );
}
```

(and link the `logUp` function to some button's click handler or something)

**Comment by aabounegm** [comment]
To explain the function name, Khaled was just complaining in general about the use of "**log** in" but "**sign** up" and demanded consistency, so consistency I granted him 😃

**Comment by aabounegm** [comment]
One thing we forgot to report: Supabase **does** support multiple response site URLs, but it doesn't support wildcards. We added https://cast-iu.pages.dev and http://localhost:3000, but we couldn't add any subdomains of the CloudFlare Pages app (something like `https://*.cast-iu.pages.dev` is not possible yet), so the auth will only work in dev and prod, but not in staging (PR previews)
